spring.datasource.url=jdbc:postgresql://postgres:5432/nectar
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=nectar
spring.datasource.password=nectar
spring.h2.console.enabled=false
spring.jpa.show-sql=false
spring.jpa.hibernate.ddl-auto=validate
spring.flyway.enabled=true
spring.kafka.bootstrap-servers=kafka:9092
spring.kafka.consumer.group-id=nectar-audit-group
spring.rabbitmq.host=rabbitmq